# Generated by Django 5.2.1 on 2025-05-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientXRayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('patient_code', models.CharField(max_length=50)),
                ('xray_id', models.CharField(max_length=50)),
                ('finding', models.TextField()),
                ('fracture_type', models.CharField(max_length=100)),
                ('affected_hand', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.patientcreatedbydoctor')),
            ],
        ),
    ]
