# Generated by Django 5.2.8 on 2025-11-28 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_migrate_patient_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient_report",
            name="patient",
        ),
        migrations.AlterModelOptions(
            name="admin",
            options={"verbose_name_plural": "Admins"},
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name_plural": "Doctors"},
        ),
        migrations.AlterModelOptions(
            name="patientcreatedbydoctor",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Patients Created By Doctor",
            },
        ),
        migrations.AlterModelOptions(
            name="patientxrayinfo",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Patient X-ray Info",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="patientcreatedbydoctor",
            new_name="main_patien_doctor__916893_idx",
            old_name="main_patientcreated_doctor_active_idx",
        ),
        migrations.RenameIndex(
            model_name="patientcreatedbydoctor",
            new_name="main_patien_fname_524d5a_idx",
            old_name="main_patientcreated_name_idx",
        ),
        migrations.RenameIndex(
            model_name="patientcreatedbydoctor",
            new_name="main_patien_email_e80305_idx",
            old_name="main_patientcreated_email_idx",
        ),
        migrations.RenameIndex(
            model_name="patientcreatedbydoctor",
            new_name="main_patien_created_65324b_idx",
            old_name="main_patientcreated_created_idx",
        ),
        migrations.RenameIndex(
            model_name="patientreport",
            new_name="main_patien_patient_391cb3_idx",
            old_name="main_patientreport_patient_date_idx",
        ),
        migrations.RenameIndex(
            model_name="patientreport",
            new_name="main_patien_patient_171a75_idx",
            old_name="main_patientreport_idx_idx",
        ),
        migrations.RenameIndex(
            model_name="patientxrayinfo",
            new_name="main_patien_patient_34d116_idx",
            old_name="main_patientxray_patient_date_idx",
        ),
        migrations.RenameIndex(
            model_name="patientxrayinfo",
            new_name="main_patien_xray_id_2bb479_idx",
            old_name="main_patientxray_id_idx",
        ),
        migrations.RenameIndex(
            model_name="patientxrayinfo",
            new_name="main_patien_fractur_986268_idx",
            old_name="main_patientxray_fracture_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="main_user_usernam_b7ac05_idx",
            old_name="main_user_username_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="main_user_user_ty_929d93_idx",
            old_name="main_user_user_type_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="main_user_email_6be720_idx",
            old_name="main_user_email_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="main_user_is_acti_82ef2c_idx",
            old_name="main_user_is_active_idx",
        ),
        migrations.AlterField(
            model_name="admin",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("user_type", "doctor"), ("user_type", "admin"), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="patientxrayinfo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="Patient_Report",
        ),
    ]
