# Generated by Django 5.2.8 on 2025-12-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0011_add_date_of_birth_to_patientxrayinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseDifficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exercise_name", models.CharField(db_index=True, max_length=200)),
                ("current_level", models.IntegerField(default=1)),
                ("reps_target", models.IntegerField(default=10)),
                ("speed_modifier", models.FloatField(default=1.0)),
                ("rom_percentage", models.IntegerField(default=100)),
                ("last_session_accuracy", models.FloatField(default=0.0)),
                ("consecutive_good_sessions", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("frame_number", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("left_shoulder_angle", models.FloatField(blank=True, null=True)),
                ("right_shoulder_angle", models.FloatField(blank=True, null=True)),
                ("left_elbow_angle", models.FloatField(blank=True, null=True)),
                ("right_elbow_angle", models.FloatField(blank=True, null=True)),
                ("left_wrist_angle", models.FloatField(blank=True, null=True)),
                ("right_wrist_angle", models.FloatField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("feedback_message", models.CharField(blank=True, max_length=500)),
                ("confidence_score", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["frame_number"],
            },
        ),
        migrations.CreateModel(
            name="PatientProgressPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("injury_type", models.CharField(max_length=100)),
                ("current_week", models.IntegerField(default=1)),
                ("total_weeks", models.IntegerField(default=6)),
                ("plan_json", models.JSONField(default=dict)),
                ("predicted_recovery_date", models.DateField(blank=True, null=True)),
                ("predicted_recovery_score", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecoveryPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("predicted_days_to_recovery", models.IntegerField()),
                ("predicted_recovery_date", models.DateField()),
                ("confidence_percentage", models.FloatField(default=0.0)),
                ("accuracy_at_prediction", models.FloatField()),
                ("sessions_completed", models.IntegerField()),
                ("days_since_injury", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("ahead", "Ahead of Schedule"),
                            ("behind", "Behind Schedule"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="patient_report",
            name="patient",
        ),
        migrations.AlterModelOptions(
            name="admin",
            options={"verbose_name_plural": "Admins"},
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name_plural": "Doctors"},
        ),
        migrations.AlterModelOptions(
            name="patientcreatedbydoctor",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Patients Created By Doctor",
            },
        ),
        migrations.AlterModelOptions(
            name="patientxrayinfo",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Patient X-ray Info",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="doctor",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exercisesession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="exercisesession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="fname",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="parents",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="show_on_dashboard",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="patientcreatedbydoctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="patientreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="patientxrayinfo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientxrayinfo",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xray_records",
                to="main.patientcreatedbydoctor",
            ),
        ),
        migrations.AlterField(
            model_name="patientxrayinfo",
            name="xray_id",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="patientcreatedbydoctor",
            index=models.Index(
                fields=["doctor", "is_active"], name="main_patien_doctor__916893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientcreatedbydoctor",
            index=models.Index(
                fields=["fname", "lname"], name="main_patien_fname_524d5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientcreatedbydoctor",
            index=models.Index(fields=["email"], name="main_patien_email_e80305_idx"),
        ),
        migrations.AddIndex(
            model_name="patientcreatedbydoctor",
            index=models.Index(
                fields=["created_at"], name="main_patien_created_65324b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientxrayinfo",
            index=models.Index(
                fields=["patient", "created_at"], name="main_patien_patient_34d116_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientxrayinfo",
            index=models.Index(
                fields=["xray_id"], name="main_patien_xray_id_2bb479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientxrayinfo",
            index=models.Index(
                fields=["fracture_type"], name="main_patien_fractur_986268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="main_user_usernam_b7ac05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="main_user_user_ty_929d93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="main_user_email_6be720_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="main_user_is_acti_82ef2c_idx"
            ),
        ),
        migrations.AddField(
            model_name="exercisedifficulty",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="difficulty_settings",
                to="main.patientcreatedbydoctor",
            ),
        ),
        migrations.AddField(
            model_name="exercisemetrics",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frame_metrics",
                to="main.exercisesession",
            ),
        ),
        migrations.AddField(
            model_name="patientprogressplan",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientprogressplan",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_plans",
                to="main.patientcreatedbydoctor",
            ),
        ),
        migrations.AddField(
            model_name="recoveryprediction",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recovery_predictions",
                to="main.patientcreatedbydoctor",
            ),
        ),
        migrations.DeleteModel(
            name="Patient_Report",
        ),
        migrations.AddIndex(
            model_name="exercisedifficulty",
            index=models.Index(
                fields=["patient", "exercise_name"],
                name="main_exerci_patient_6e4f82_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exercisedifficulty",
            unique_together={("patient", "exercise_name")},
        ),
        migrations.AddIndex(
            model_name="exercisemetrics",
            index=models.Index(
                fields=["session", "frame_number"],
                name="main_exerci_session_852058_idx",
            ),
        ),
    ]
