# Generated by Django 5.2.8 on 2025-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_exercisedifficulty_exercisemetrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="fname",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="lname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="medical_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
