version = 5.2.1
archive_dir = /etc/letsencrypt/archive/medxai.duckdns.org
cert = /etc/letsencrypt/live/medxai.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/medxai.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/medxai.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/medxai.duckdns.org/fullchain.pem
[renewalparams]
account = fc93ce498d15703dccb48e1dd238e5fd
pref_challs = http-01,
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2025-12-08T20:09:26
